### ISSUE TITLE
blank screen on arm7 qnap

### ISSUE THREAD

**Issue by SiNaPsEr0x** [DesktopContainers/base-alpine#1]
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/5438823/130067114-1b2c5a44-0320-4ae2-b1db-782aee70da19.png">

this error
 12:15:44 x11vnc version: 0.9.16 lastmod: 2019-01-05  pid: 41
19/08/2021 12:15:44 Using X display :0
19/08/2021 12:15:44 rootwin: 0x43 reswin: 0x400001 dpy: 0x75b55080
19/08/2021 12:15:44 
19/08/2021 12:15:44 ------------------ USEFUL INFORMATION ------------------
19/08/2021 12:15:44 X DAMAGE available on display, using it for polling hints.
19/08/2021 12:15:44   To disable this behavior use: '-noxdamage'
19/08/2021 12:15:44 
19/08/2021 12:15:44   Most compositing window managers like 'compiz' or 'beryl'
19/08/2021 12:15:44   cause X DAMAGE to fail, and so you may not see any screen
19/08/2021 12:15:44   updates via VNC.  Either disable 'compiz' (recommended) or
19/08/2021 12:15:44   supply the x11vnc '-noxdamage' command line option.
19/08/2021 12:15:44 
19/08/2021 12:15:44 Wireframing: -wireframe mode is in effect for window moves.
19/08/2021 12:15:44   If this yields undesired behavior (poor response, painting
19/08/2021 12:15:44   errors, etc) it may be disabled:
19/08/2021 12:15:44    - use '-nowf' to disable wireframing completely.
19/08/2021 12:15:44    - use '-nowcr' to disable the Copy Rectangle after the
19/08/2021 12:15:44      moved window is released in the new position.
19/08/2021 12:15:44   Also see the -help entry for tuning parameters.
19/08/2021 12:15:44   You can press 3 Alt_L's (Left "Alt" key) in a row to 
19/08/2021 12:15:44   repaint the screen, also see the -fixscreen option for
19/08/2021 12:15:44   periodic repaints.
19/08/2021 12:15:44 
19/08/2021 12:15:44 XFIXES available on display, resetting cursor mode
19/08/2021 12:15:44   to: '-cursor most'.
19/08/2021 12:15:44   to disable this behavior use: '-cursor arrow'
19/08/2021 12:15:44   or '-noxfixes'.
19/08/2021 12:15:44 using XFIXES for cursor drawing.
19/08/2021 12:15:44 GrabServer control via XTEST.
19/08/2021 12:15:44

**Comment by MarvAmBass** [comment]
black screen is not a sign for a problem.

it uses openbox in the default configuration - you can use a secondary mouseclick to open the openbox menu

if this works - the container does everything it's supposed to do

**Comment by SiNaPsEr0x** [comment]
my error
